### ISSUE TITLE
Limit on Number of images

### ISSUE THREAD

**Issue by imAnjithreddy** [96AA48/node-stocksnap.io#1]
Is there any limit on the number of request made.?

**Comment by 96AA48** [comment]
Hey @imAnjithreddy! I don't know as of now if there is any limit to obtaining images through Stocksnap.io. I haven't found that limit yet, but this module only get's a low-res version of the image, not the full resolution one. 

While this is possible by `POST`ing to a specific address with two `csrf` tokens, I haven't added it to the module.

Does this answer your question?

**Comment by imAnjithreddy** [comment]
Thank you :)
